### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-labradorita#1]
Cool job @labradorita !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the language of the page
- [x] Why is the body tag empty?
- [x] We need only one h1 tag

## CSS - selectors
- [x] Class selectors are free, let's use them instead tag selectors 

## CSS - box model
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)

## CSS - other
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Remove commented CSS rules

## Assets
- [x] Use relative routes like `./styles/main.css`.

## Good practices
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Write your classes in English!
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] If you use justify-content you should use display: flex (https://github.com/Adalab/m1-evaluacion-intermedia-labradorita/blob/master/styles/style.css#L15)
- [x] Why do we use position: relative? https://github.com/Adalab/m1-evaluacion-intermedia-labradorita/blob/master/styles/style.css#L32

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

## Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
En general buen trabajo, pero hay una cosa que no nos debería volver a pasar y es dejar el body vacío. 

![Good job](https://media.giphy.com/media/l41YqNeoHIVsBHEnm/giphy.gif)

**Comment by labradorita** [comment]
Hola Miguel! Creo que ya he realizado todas las correcciones en el ejercicio. Aunque tengo algunas dudas:
- ¿Hace falta cambiar el mensaje de los commits anteriores?
- Al guardar en VisualCode, automáticamente me crea algunos espacios en sitios en los que parece que ayudan a la lectura del código. Si quiero que se guarden los cambios tengo que pasar por ello.
Y bueno....lo del body no tiene nombre....espero haberlo grabado a fuego jejeje. Por eso no me hacía margin 0 en el header y me quedaba un poco más abajo. 
Un saludo y gracias por las correcciones!

**Comment by migueldelmazo** [comment]
Hola @labradorita no hace falta cambiar los commits antiguos.

Qué bonito y elegante queda ahora el código, se lee fácilmente y se entiende!!! Muy buen trabajo Raquel!!!

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
